language: node_js
node_js:
- node
cache: yarn
install:
- npm install --global --upgrade yarn
- yarn install
jobs:
  include:
  - stage: Lint
    if: type = push
    script:
    - yarn outdated
    - yarn foia-db
    - yarn gulp build
  - stage: Release
    if: type = api
    script:
    - yarn foia-db --compile
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
