language: node_js
node_js:
- node
cache: yarn
install:
- npm install --global --upgrade yarn
- yarn install
- wget https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip
- unzip terraform_0.12.0_linux_amd64.zip
- rm terraform_0.12.0_linux_amd64.zip
jobs:
  include:
  - stage: Build
    if: ( type = push ) AND ( branch != master )
    script:
    - yarn gulp build
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform plan
  - stage: Deploy
    if: ( type = push ) AND ( branch = master )
    script:
    - yarn gulp build
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform apply -auto-approve
  - stage: Unity
    if: ( type = push ) AND ( branch != master )
    os: osx
    osx_image: xcode10.2
    script:
    - wget --progress=dot:mega https://download.unity3d.com/download_unity/dc414eb9ed43/MacEditorInstaller/Unity.pkg
    - sudo installer -package Unity.pkg -target /
    - /Applications/Unity/Unity.app/Contents/MacOS/Unity -username "$UNITY_USER" -password "$UNITY_PASSWORD" -nographics -batchmode -silent-crashes -force-free -projectPath Unity/ -quit || true
