language: node_js
node_js:
- node
cache: yarn
install:
- npm install --global --upgrade yarn
- yarn install
jobs:
  include:
  - stage: Lint
    if: ( type = push ) AND ( branch != master )
    script:
    - yarn outdated
    - yarn foia-db
    - yarn gulp build
  - stage: Deploy
    if: ( type = push ) AND ( branch = master )
    script:
    - yarn gulp build
    - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    - unzip terraform_0.11.7_linux_amd64.zip
    - rm terraform_0.11.7_linux_amd64.zip
    - ./terraform init
    - ./terraform apply -auto-approve
  - stage: Actualize
    if: type = api
    script:
    - yarn foia-db --compile
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
